"""empty message

Revision ID: 83c943a93df2
Revises: 
Create Date: 2024-06-04 05:50:35.517817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c943a93df2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('birth_date <= CURRENT_DATE', name='check_birth_date'),
    sa.CheckConstraint('length(full_name) <= 200'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id', name='actor_unique_imdb_id')
    )
    op.create_table('films',
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('imdb_rating >= 0 and imdb_rating <= 10', name='imdb_rating_more_than_or_equal_0_and_less_than_or_equal_10'),
    sa.CheckConstraint('length(title) <= 200', name='title_length_less_than_or_equal_200'),
    sa.CheckConstraint('year >= 1895', name='year_more_than_or_equal_1895'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id', name='film_unique_imdb_id')
    )
    op.create_table('film_to_actor',
    sa.Column('film_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('character', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_to_actor')
    op.drop_table('films')
    op.drop_table('actors')
    # ### end Alembic commands ###
