"""empty message

Revision ID: bf6c4326a69c
Revises: 
Create Date: 2024-06-02 00:57:27.541175

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf6c4326a69c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('imbd_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(full_name) <= 200'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imbd_id', name='actor_unique_imbd_id')
    )
    op.create_table('films',
    sa.Column('imbd_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('imdb_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('imdb_rating >= 0 and imdb_rating <= 10'),
    sa.CheckConstraint('length(title) <= 200'),
    sa.CheckConstraint('year >= 1895'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imbd_id', name='film_unique_imbd_id')
    )
    op.create_table('film_to_actor',
    sa.Column('film_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_to_actor')
    op.drop_table('films')
    op.drop_table('actors')
    # ### end Alembic commands ###
